platform :osx, '10.15'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

flutter_root = ENV['FLUTTER_ROOT']
if flutter_root.nil? || flutter_root.empty?
  generated_xcode_build_settings_path = File.expand_path(File.join('Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __dir__)
  if File.exist?(generated_xcode_build_settings_path)
    File.foreach(generated_xcode_build_settings_path) do |line|
      matches = line.match(/FLUTTER_ROOT\=(.*)/)
      flutter_root = matches[1].strip if matches
    end
  end
end
raise 'FLUTTER_ROOT not found. Set FLUTTER_ROOT env var or run flutter pub get first.' if flutter_root.nil? || flutter_root.empty?

require File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

flutter_macos_podfile_setup

target 'Runner' do
  use_modular_headers!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      config.build_settings['CLANG_WARN_TREAT_WARNINGS_AS_ERRORS'] = 'NO'

      cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited)'
      unless cflags.include?('-Wno-missing-template-arg-list-after-template-kw')
        config.build_settings['OTHER_CFLAGS'] = "#{cflags} -Wno-missing-template-arg-list-after-template-kw"
      end

      cxxflags = config.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
      unless cxxflags.include?('-Wno-missing-template-arg-list-after-template-kw')
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = "#{cxxflags} -Wno-missing-template-arg-list-after-template-kw"
      end
    end

    if target.name == 'BoringSSL-GRPC' || target.name == 'BoringSSL'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          file.settings['COMPILER_FLAGS'] = file.settings['COMPILER_FLAGS'].gsub(' -GCC_WARN_INHIBIT_ALL_WARNINGS', '')
        end
      end
    end

    if target.name == 'gRPC-C++'
      grpc_hdr = File.join(installer.sandbox.root, 'gRPC-C++', 'src', 'core', 'lib', 'promise', 'detail', 'basic_seq.h')
      if File.exist?(grpc_hdr)
        content = File.read(grpc_hdr)
        unless content.include?('CallSeqFactory<>')
          content.gsub!('Traits::template CallSeqFactory(', 'Traits::template CallSeqFactory<>(')
          File.write(grpc_hdr, content)
          puts "Patched gRPC-C++ basic_seq.h template keyword"
        end
      end
    end
  end
end
